name: 'IQGeo test action'
description: 'test echo commands'

runs:
    using: "composite"
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: Echo success
        shell: bash
        run: |
          echo "Hit test action in actions repo"
